// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVwsBkYU0dTLic0Z03JdTfR6XYrKyTkB8',
    appId: '1:353744236650:web:139b3a490cc3a894e71a13',
    messagingSenderId: '353744236650',
    projectId: 'projeto-flutter-9ab7f',
    authDomain: 'projeto-flutter-9ab7f.firebaseapp.com',
    storageBucket: 'projeto-flutter-9ab7f.appspot.com',
    measurementId: 'G-Y39H39VLGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWEGzSSXWu4-ttlgWwInUxgBilMc1pwMY',
    appId: '1:353744236650:android:0db1871ec35f34c1e71a13',
    messagingSenderId: '353744236650',
    projectId: 'projeto-flutter-9ab7f',
    storageBucket: 'projeto-flutter-9ab7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUFdAFQBsGjHLe5z4z21xoUYVOEpD_o3o',
    appId: '1:353744236650:ios:f6e64ee864aba955e71a13',
    messagingSenderId: '353744236650',
    projectId: 'projeto-flutter-9ab7f',
    storageBucket: 'projeto-flutter-9ab7f.appspot.com',
    iosClientId: '353744236650-bsp5voc66pluhb6m0ifmm8glsmutspci.apps.googleusercontent.com',
    iosBundleId: 'com.example.incident',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUFdAFQBsGjHLe5z4z21xoUYVOEpD_o3o',
    appId: '1:353744236650:ios:c1ad57c72b989df0e71a13',
    messagingSenderId: '353744236650',
    projectId: 'projeto-flutter-9ab7f',
    storageBucket: 'projeto-flutter-9ab7f.appspot.com',
    iosClientId: '353744236650-dt7ljaem39dqtv43nm724d92ft7hs4i6.apps.googleusercontent.com',
    iosBundleId: 'com.example.incident.RunnerTests',
  );
}
